backend/main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store')),
    path('',include('userProfile.urls',namespace='vendor_detail'))
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/store/urls.py
from django.urls import re_path ,path 
from store.views import index,product_detail,department_categories,category,search_product,cart,add_to_cart
from store.views import remove_from_cart,change_quantity,checkout_page


app_name='store'

urlpatterns=[
    path('',index,name='home'),
    path('product/<int:id>/',product_detail,name='Product_detail'),
    path('department-categories/',department_categories,name='Department_Categories'),
    path('category/<str:slug>/',category,name='category_detail'),
    path('search/',search_product,name='search_product'),
    path('cart/',cart,name='cart_view'),
    path('add_to_cart/<int:product_id>/',add_to_cart,name='add_to_cart'),
    path("remove-from-cart/<str:product_id>/",remove_from_cart,name='remove_from_cart'),
    path('change_quantity/<str:product_id>/',change_quantity,name='change_quantity'),
    path('checkout/',checkout_page,name='checkout'),

]

backend/store/models.py
from django.db import models
from django.contrib.auth.models import User
from io import BytesIO
from PIL import Image
from django.core.files import File
from userProfile.models import Pasal
from django.core.validators import MaxValueValidator


class Main_Navigation(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    ordering = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='Main Navigation'
        verbose_name_plural="Main Navigations"
        ordering = ['ordering']

# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    ordering = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='Category'
        verbose_name_plural="Categories"
        ordering = ['ordering']

 
class Product(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL = 'waitingapproval'
    ACTIVE = 'active'
    DELETED = 'deleted'
    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    vendor = models.ForeignKey(Pasal, related_name='products', on_delete=models.CASCADE,null=True)
    added_by=models.ForeignKey(User,related_name='products',on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/', blank=True, null=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)

    class Meta:
        ordering = ['-date_added']
    
    def __str__(self):
        return f'{self.title } {self.status}'
    
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/240x180.jpg'
    
    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)
        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)
        thumbnail = File(thumb_io, name=image.name)

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Order(models.Model):
    ORDERED='ordered'
    PACKAGING='packagig'
    SHIPPED='shipped]'
    STATUS_CHOICES=(
        ( ORDERED,'Ordered'),
        (  PACKAGING,'Packaging'),
        ( SHIPPED,'Shipped'),
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status=models.CharField(max_length=20,choices=STATUS_CHOICES,default=ORDERED)

    def __str__(self):
        return f'{self.created_by} :- at {self.created_at} {self.status}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
    
    def get_display_price(self):
        return self.price / 100
    

class FeaturedProduct(models.Model):
    product=models.ForeignKey(Product,related_name='featured_product',on_delete=models.CASCADE)
    def __str__(self):
        return self.product.title
    

class ProductReview(models.Model):
    product=models.ForeignKey(Product,related_name='review',on_delete=models.CASCADE)
    user=models.ForeignKey(User,related_name='product_review',on_delete=models.CASCADE)
    rating = models.SmallIntegerField(validators=[MaxValueValidator(5)])
    comment=models.CharField(max_length=200)

    def __str__(self):
        return self.user.username, self.product.title ,self.rating

backend/store/forms.py
import django
from django import forms
from store.models import Product,Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'zipcode', 'city']

backend/store/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.contrib import messages
import tensorflow
from django.contrib.auth.decorators import login_required
from io import BytesIO
from .models import Product,Category,Order,OrderItem,CartItem,FeaturedProduct
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from .cart import Cart 
from store.forms import OrderForm


# Load the VGG16 model and remove the last layer
# vgg_model = vgg16.VGG16(weights='imagenet', include_top=False)
# Create your views here.
model = MobileNetV2(weights='imagenet')
def index(request):
    products=Product.objects.filter(status=Product.ACTIVE)
    featured_products=FeaturedProduct.objects.all().filter(product__status=Product.ACTIVE)
    context={
        'products':products,
        'featured_products':featured_products
    }
    return render(request, 'front_page.html',context)

def product_detail(request,id):
    product=Product.objects.filter(status=Product.ACTIVE).get(id=id)
    cart=Cart(request)
    context={
        'product':product
    }
    return render(request, 'store/product_details.html',context)

def department_categories(request):
    categories=Category.objects.all()
    context={ 
        'categories':categories
    }
    return render(request, 'store/all_categories.html',context)

def category(request,slug):
    category=Category.objects.get(slug=slug)
    category_product=category.products.filter(status=Product.ACTIVE)
    context={
        'category':category,
        'products':category_product
    }
    return render(request, 'store/category.html',context)

def feature_extractor(img):
    model = MobileNetV2(weights='imagenet', include_top=False, pooling='avg')
    x = img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    features = model.predict(x)[0]
    return features

def search_product(request):
    if request.method == 'POST':
        image = request.FILES.get('image')
        if image:
            # Load the query image and extract features
            img_bytes = image.read()
            img = load_img(BytesIO(img_bytes), target_size=(224, 224))
            query_features = feature_extractor(img)

            # Retrieve all products from the database and compute similarities
            all_products = Product.objects.filter(status=Product.ACTIVE)
            similarities = []
            for product in all_products:
                # Load the image and extract features
                if product.image:
                    img_bytes = product.image.read()
                    img = load_img(BytesIO(img_bytes), target_size=(224, 224))
                    features = feature_extractor(img)

                    # Compute similarity between the query and the image
                    similarity = cosine_similarity(query_features.reshape(1, -1), features.reshape(1, -1))[0][0]
                    similarities.append((product, similarity))

            # Sort products by similarity and display the results
            sorted_products = sorted(similarities, key=lambda x: x[1], reverse=True)
            context = {
                'query': image,
                'products': [{'id': p.id, 'title': p.title, 'image': p.image.url, 'similarity': s} for p, s in sorted_products]
            }
            return render(request, 'store/search.html', context)
    else:
        # If the request method is not POST or an image was not uploaded, display the search form
        return render(request, 'front_page.html')






def cart(request):
    cart = Cart(request)
    return render(request, 'store/cart_view.html', {'cart': cart })

def change_quantity(request, product_id):
    action = request.GET.get('action', '')
        
    if action:
        quantity = 1

        if action == 'decrease':
            quantity = -1

        cart = Cart(request)
        cart.add(product_id, quantity, True)
    
    return redirect('store:cart_view')

def add_to_cart(request, product_id):

    cart = Cart(request)
    cart.add(product_id)
   
    return redirect(reverse('store:Product_detail',args=[product_id]))
def remove_from_cart(request, product_id):
    cart = Cart(request)
    print(cart)
    print(product_id)
    cart.remove(product_id)
    return redirect('store:cart_view')

@login_required(login_url='/login/',redirect_field_name='next')
def checkout_page(request):
    cart=Cart(request)
    total_price=cart.get_total_cost()
    if request.method == "POST":
        form=OrderForm(request.POST)
        if form.is_valid():
            
            for item in cart:
                product=item['product']
                total_price+=product.price*int (item['quantity'])
            order=form.save(commit=False)
            order.created_by=request.user
            order.paid_amount=total_price
            order.save()

            for item in cart:
                product=item['product']
                quantity=int(item['quantity'])
                price=product.price*quantity
                item=OrderItem.objects.create(order=order,product=product,quantity=quantity,price=price)
            cart.clear()
            messages.success(request, 'Your order is placed')

            return redirect("userProfile:my_account")
    else:
      
        form=OrderForm()
    
    context={
        'total_price':total_price,
        'form': form
    }

    return render(request,'store/checkout.html',context)

backend/store/templates/store/all_categories.html
{% extends 'base.html'%}

{% block main_content %}
<main class="w-11/12 mx-auto">
    {% for category in categories%}
  
        <a href="{% url 'store:category_detail' category.id}" class="text-2xl px-3 inline-block py-2 bg-indigo-200 text-black">{{category.title}} hell</h2>
    
    {% endfor %}
</main>
{% endblock%}

backend/store/templates/store/cart_view.html
{% extends 'base.html'%}

{% block main_content %}
<main class="w-10/12 mx-auto">
   {% if  cart %}
    <h2 class="text-2xl my-2 font-medium text-gray-500">Your Cart</h2>
    <div class="cart_details">
    <!-- component -->
<section class="antialiased bg-gray-100 text-gray-600 h-screen px-4">
    <div class="flex flex-col justify-center h-full">
        <!-- Table -->
        <div class="w-full max-w-2xl mx-auto bg-white shadow-lg rounded-sm border border-gray-200">
            <header class="px-5 py-4 border-b border-gray-100">
                <h2 class="font-semibold text-gray-800">Customers</h2>
            </header>
            <div class="p-3">
                <div class="overflow-x-auto">
                    <table class="table-auto w-full">
                        <thead class="text-xs font-semibold uppercase text-gray-400 bg-gray-50">
                            <tr>
                                <th class="p-2 whitespace-nowrap">
                                    <div class="font-semibold text-left">Product</div>
                                </th>
                                <th class="p-2 whitespace-nowrap">
                                    <div class="font-semibold text-left">Price</div>
                                </th>
                                <th class="p-2 whitespace-nowrap">
                                    <div class="font-semibold text-left">Quantity</div>
                                </th>
                                <th class="p-2 whitespace-nowrap">
                                    <div class="font-semibold text-center">Remove</div>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="text-sm divide-y divide-gray-100">
                            {% for item in cart %}
                            
                           
                            <tr>
                                <td class="p-2 whitespace-nowrap">
                                    <div class="flex items-center">
                                       {% if item.product.image %} <div class="w-10 h-10 flex-shrink-0 mr-2 sm:mr-3"><img class="rounded-full" src={{item.product.image.url}} width="40" height="40" alt="Alex Shatov"></div>{%endif%}
                                        <div class="font-medium text-gray-800">{{item.product.title}}</div>
                                    </div>
                                </td>
                                <td class="p-2 whitespace-nowrap">
                                    <div class="text-left"> {{item.product.price}}</div>
                                </td>
                                <td class="p-2 whitespace-nowrap">
                                   <a class="bg-indigo-400 px-2 py-1" href="{% url 'store:change_quantity' item.product.id %}?action=increase"> +</a>
                                    <div class="text-left font-medium text-green-500">{{item.quantity}}</div>
                                    <a class="bg-indigo-400 px-2 py-1" href="{% url 'store:change_quantity' item.product.id %}?action=decrease"> 
                                        -
                                    </a>
                                </td>
                                <td class="p-2 whitespace-nowrap">
                                    <a class="text-pink-500" href="{% url 'store:remove_from_cart' item.product.id %}" class="text-lg text-center"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                      </svg>
                                      </a>
                                </td>
                            </tr>
                            {%endfor%}
                           
                           
                        </tbody>
                       
                    </table>
                    <div class="flex justify-between px-10 mx-auto  py-5">
                        <p class=" space-evenly"> <strong> Total:</strong> </p>
                        <span>{{cart.get_total_cost}}</span>
                     
                       
                        
                    </div>
                    <div class="bg-indigo-400 text-white text-xl my-2 mx-2 px-5 rounded py-5 w-6/12 mx-auto text-center">
                       <a href="{% url 'store:checkout' %}" class="href">Proced Checkout</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
   {% else %}
    </div>  
    <h2 class="text-2xl my-2 font-medium text-gray-500">Your Cart is empty... Shop Now!!</h2>
{% endif %}
</main>
{% endblock%}

backend/store/templates/store/category.html
{% extends 'base.html'%}

{% block main_content %}
<main class="w-11/12 mx-auto bg-gray-100">
   
    <h2 class="text-2xl text-center ">{{category.title}}  </h2>
           {%include 'includes/partial_Product.html' %}
    </div>

</main>
{% endblock%}

backend/store/templates/store/checkout.html
{% extends 'base.html'%}
{% load widget_tweaks %}
{% block main_content %}
<main class="w-10/12 mx-auto">
    {% if messages %}
    <div id="messages">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    </div>
  {%endif %}
   
   {% if  cart %}
  <h2> Toatal Price : Rs.{{total_price}} </h2>

  <form method="post" class="w-4/5 mx-auto" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label for="{{ form.first_name.id_for_label }}" class="block text-gray-700 font-bold mb-2">First Name</label>
        {{ form.first_name|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
    </div>
    <div class="mb-4">
        <label for="{{ form.last_name.id_for_label }}" class="block text-gray-700 font-bold mb-2">Last Name</label>
        {{ form.last_name|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
    </div>
    <div class="mb-4">
        <label for="{{ form.address.id_for_label }}" class="block text-gray-700 font-bold mb-2">Address</label>
        {{ form.address|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
    </div>
    <div class="mb-4 flex gap-2 items-center">
        <div class=>
        <label for="{{ form.zipcode.id_for_label }}" class="block text-gray-700 font-bold mb-2">Zipcode</label>
        {{ form.zipcode|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
         </div>
         <div class=>
            <label for="{{ form.zipcode.id_for_label }}" class="block text-gray-700 font-bold mb-2">City</label>
            {{ form.city|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
             </div>
    </div>
   
    <div class="flex justify-between">
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Proceed Order</button>
 
</div>
</form>


   {% else %}
    </div>  
    <h2 class="text-2xl my-2 font-medium text-gray-500">Your Cart is empty... Shop Now!!</h2>
{% endif %}
</main>
{% endblock%}

backend/store/templates/store/product_details.html
{% extends 'base.html' %}
{% block main_content %} 

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        {% if product.image %}
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{product.image.url}}">
        {%endif%}
        <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">{{product.category}}</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{product.title}}</h1>
          <div class="flex mb-4">
            <span class="flex items-center">
              <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
              </svg>
              <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
              </svg>
              <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-widtAh="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
              </svg>
              <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
              </svg>
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 text-indigo-500" viewBox="0 0 24 24">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"></path>
              </svg>
              <span class="text-gray-600 ml-3">4 Reviews</span>
            </span>
            <span class="flex ml-3 pl-3 py-2 border-l-2 border-gray-200 space-x-2s">
              <a class="text-gray-500">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                </svg>
              </a>
              <a class="text-gray-500">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                </svg>
              </a>
              <a class="text-gray-500">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                </svg>
              </a>
            </span>
          </div>
          <p class="leading-relaxed">{% firstof product.added_by.get_full_name product.added_by.username %}</p>
          <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-100 mb-5">
            <div class="flex">
              <span class="mr-3">Color</span>
              <button class="border-2 border-gray-300 rounded-full w-6 h-6 focus:outline-none"></button>
              <button class="border-2 border-gray-300 ml-1 bg-gray-700 rounded-full w-6 h-6 focus:outline-none"></button>
              <button class="border-2 border-gray-300 ml-1 bg-indigo-500 rounded-full w-6 h-6 focus:outline-none"></button>
            </div>
            <div class="flex ml-6 items-center">
              <span class="mr-3">Size</span>
              <div class="relative">
               
                <span class="absolute right-0 top-0 h-full w-10 text-center text-gray-600 pointer-events-none flex items-center justify-center">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4" viewBox="0 0 24 24">
                    <path d="M6 9l6 6 6-6"></path>
                  </svg>
                </span>
              </div>
            </div>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">Rs.{{product.price}}</span>
         <a href="{% url 'store:add_to_cart' product.id %}"  class=" flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded items-center"> <span class="iconify mr-1" data-icon="mdi-cart-plus"></span> Add to cart</a>
            <a href="{% url 'store:checkout'%}" class="flex ml-auto text-indigo-500 border-0 py-2 px-6  outline rounded  items-center">Buy Now</a>

            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          </div>
          <p>{{product.description}}</p>
        </div>
      </div>
      
    </div>
    
  </section>
{% endblock %}

backend/store/templates/store/search.html
{% extends 'base.html'%}

{% block main_content %}
<main class="w-11/12 mx-auto">
   
    <p class="my-2">Showing results for {{query}}</p>
    <div class="flex flex-wrap -m-4">
        {% if products %}
            {% for product in products %}
                {% if product.similarity > 0.5 %}
                    <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                        <a href="{% url 'store:Product_detail' product.id %}" class="block relative h-48 rounded overflow-hidden">
                            <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{{product.image}}">
                        </a>
                        <a href="{% url 'store:Product_detail' product.id %}">
                            <div class="mt-4">
                                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.category}}</h3>
                                <h2 class="text-gray-900 title-font text-lg font-medium">{{product.title}}</h2>
                                <p class="mt-1">Similarity score: {{product.similarity}}</p>
                            </div>
                        </a>
                    </div>
                   
                {% endif %}
                
            {% endfor %}
        {% else %}
            <p class="my-1/2 bg-orange-500 text-white text-2xl">No products found!! Please input another image.</p>
        {% endif %}
    </div>

</main>
{% endblock%}