backend/main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store')),
    path('',include('userProfile.urls',namespace='vendor_detail'))
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/store/urls.py
from django.urls import re_path ,path 
from store.views import index,product_detail,department_categories,category,search_product,cart,add_to_cart
from store.views import remove_from_cart,change_quantity,checkout_page


app_name='store'

urlpatterns=[
    path('',index,name='home'),
    path('product/<int:id>/',product_detail,name='Product_detail'),
    path('department-categories/',department_categories,name='Department_Categories'),
    path('category/<str:slug>/',category,name='category_detail'),
    path('search/',search_product,name='search_product'),
    path('cart/',cart,name='cart_view'),
    path('add_to_cart/<int:product_id>/',add_to_cart,name='add_to_cart'),
    path("remove-from-cart/<str:product_id>/",remove_from_cart,name='remove_from_cart'),
    path('change_quantity/<str:product_id>/',change_quantity,name='change_quantity'),
    path('checkout/',checkout_page,name='checkout'),

]

backend/userProfile/urls.py
from django.urls import path
from userProfile.views import signup,my_account
from userProfile.views import my_store
from userProfile.views import add_product,edit_product,delete_product
from .views import vendor_detail 
from django.contrib.auth import views as auth_views


app_name='userProfile'

urlpatterns=[
    path('vendors/<int:pk>', vendor_detail,name='vendor_detail'),
    path('signup/', signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='user_profile/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('my_account/', my_account,name='my_account'),
    path('my_store/', my_store,name='my_store'),
    path('add_product/',add_product,name='add_product'),
    path('edit_product/<int:id>/',edit_product,name='edit_product'),
    path('delete_product/<int:id>/',delete_product,name='delete_product'),
]

backend/store/models.py
from django.db import models
from django.contrib.auth.models import User
from io import BytesIO
from PIL import Image
from django.core.files import File
from userProfile.models import Pasal
from django.core.validators import MaxValueValidator


class Main_Navigation(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    ordering = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='Main Navigation'
        verbose_name_plural="Main Navigations"
        ordering = ['ordering']

# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    ordering = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='Category'
        verbose_name_plural="Categories"
        ordering = ['ordering']

 
class Product(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL = 'waitingapproval'
    ACTIVE = 'active'
    DELETED = 'deleted'
    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    vendor = models.ForeignKey(Pasal, related_name='products', on_delete=models.CASCADE,null=True)
    added_by=models.ForeignKey(User,related_name='products',on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/', blank=True, null=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)

    class Meta:
        ordering = ['-date_added']
    
    def __str__(self):
        return f'{self.title } {self.status}'
    
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/240x180.jpg'
    
    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)
        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)
        thumbnail = File(thumb_io, name=image.name)

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Order(models.Model):
    ORDERED='ordered'
    PACKAGING='packagig'
    SHIPPED='shipped]'
    STATUS_CHOICES=(
        ( ORDERED,'Ordered'),
        (  PACKAGING,'Packaging'),
        ( SHIPPED,'Shipped'),
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status=models.CharField(max_length=20,choices=STATUS_CHOICES,default=ORDERED)

    def __str__(self):
        return f'{self.created_by} :- at {self.created_at} {self.status}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
    
    def get_display_price(self):
        return self.price / 100
    

class FeaturedProduct(models.Model):
    product=models.ForeignKey(Product,related_name='featured_product',on_delete=models.CASCADE)
    def __str__(self):
        return self.product.title
    

class ProductReview(models.Model):
    product=models.ForeignKey(Product,related_name='review',on_delete=models.CASCADE)
    user=models.ForeignKey(User,related_name='product_review',on_delete=models.CASCADE)
    rating = models.SmallIntegerField(validators=[MaxValueValidator(5)])
    comment=models.CharField(max_length=200)

    def __str__(self):
        return self.user.username, self.product.title ,self.rating

backend/store/forms.py
import django
from django import forms
from store.models import Product,Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'zipcode', 'city']

backend/store/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.contrib import messages
import tensorflow
from django.contrib.auth.decorators import login_required
from io import BytesIO
from .models import Product,Category,Order,OrderItem,CartItem,FeaturedProduct
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from .cart import Cart 
from store.forms import OrderForm


# Load the VGG16 model and remove the last layer
# vgg_model = vgg16.VGG16(weights='imagenet', include_top=False)
# Create your views here.
model = MobileNetV2(weights='imagenet')
def index(request):
    products=Product.objects.filter(status=Product.ACTIVE)
    featured_products=FeaturedProduct.objects.all().filter(product__status=Product.ACTIVE)
    context={
        'products':products,
        'featured_products':featured_products
    }
    return render(request, 'front_page.html',context)

def product_detail(request,id):
    product=Product.objects.filter(status=Product.ACTIVE).get(id=id)
    cart=Cart(request)
    context={
        'product':product
    }
    return render(request, 'store/product_details.html',context)

def department_categories(request):
    categories=Category.objects.all()
    context={ 
        'categories':categories
    }
    return render(request, 'store/all_categories.html',context)

def category(request,slug):
    category=Category.objects.get(slug=slug)
    category_product=category.products.filter(status=Product.ACTIVE)
    context={
        'category':category,
        'products':category_product
    }
    return render(request, 'store/category.html',context)

def feature_extractor(img):
    model = MobileNetV2(weights='imagenet', include_top=False, pooling='avg')
    x = img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    features = model.predict(x)[0]
    return features

def search_product(request):
    if request.method == 'POST':
        image = request.FILES.get('image')
        if image:
            # Load the query image and extract features
            img_bytes = image.read()
            img = load_img(BytesIO(img_bytes), target_size=(224, 224))
            query_features = feature_extractor(img)

            # Retrieve all products from the database and compute similarities
            all_products = Product.objects.filter(status=Product.ACTIVE)
            similarities = []
            for product in all_products:
                # Load the image and extract features
                if product.image:
                    img_bytes = product.image.read()
                    img = load_img(BytesIO(img_bytes), target_size=(224, 224))
                    features = feature_extractor(img)

                    # Compute similarity between the query and the image
                    similarity = cosine_similarity(query_features.reshape(1, -1), features.reshape(1, -1))[0][0]
                    similarities.append((product, similarity))

            # Sort products by similarity and display the results
            sorted_products = sorted(similarities, key=lambda x: x[1], reverse=True)
            context = {
                'query': image,
                'products': [{'id': p.id, 'title': p.title, 'image': p.image.url, 'similarity': s} for p, s in sorted_products]
            }
            return render(request, 'store/search.html', context)
    else:
        # If the request method is not POST or an image was not uploaded, display the search form
        return render(request, 'front_page.html')






def cart(request):
    cart = Cart(request)
    return render(request, 'store/cart_view.html', {'cart': cart })

def change_quantity(request, product_id):
    action = request.GET.get('action', '')
        
    if action:
        quantity = 1

        if action == 'decrease':
            quantity = -1

        cart = Cart(request)
        cart.add(product_id, quantity, True)
    
    return redirect('store:cart_view')

def add_to_cart(request, product_id):

    cart = Cart(request)
    cart.add(product_id)
   
    return redirect(reverse('store:Product_detail',args=[product_id]))
def remove_from_cart(request, product_id):
    cart = Cart(request)
    print(cart)
    print(product_id)
    cart.remove(product_id)
    return redirect('store:cart_view')

@login_required(login_url='/login/',redirect_field_name='next')
def checkout_page(request):
    cart=Cart(request)
    total_price=cart.get_total_cost()
    if request.method == "POST":
        form=OrderForm(request.POST)
        if form.is_valid():
            
            for item in cart:
                product=item['product']
                total_price+=product.price*int (item['quantity'])
            order=form.save(commit=False)
            order.created_by=request.user
            order.paid_amount=total_price
            order.save()

            for item in cart:
                product=item['product']
                quantity=int(item['quantity'])
                price=product.price*quantity
                item=OrderItem.objects.create(order=order,product=product,quantity=quantity,price=price)
            cart.clear()
            messages.success(request, 'Your order is placed')

            return redirect("userProfile:my_account")
    else:
      
        form=OrderForm()
    
    context={
        'total_price':total_price,
        'form': form
    }

    return render(request,'store/checkout.html',context)

backend/store/templates/includes/department_category_nav.html
{% for nav in categories %}
<a  href="{% url 'store:category_detail' nav.slug %}" class="mr-5 my-1 border-b hover:border-b hover:border-green-500 hover:text-gray-900">{{nav.title}}</a>
{% endfor %}

backend/store/templates/includes/header.html
{% load static %}
{% load main_nav%}
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center border-b">
      <a href="{%url 'store:home'%}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <img src="{% static 'assets/Mart_blaster_logo.png' %}" class="w-20 h-20 text-white " />
       
        <div class="ml-1 text-2xl ">MART<span class="text-orange-700 text-2xl">BLASTER</span></div>
      </a>
      <!-- Search form -->
      <div class="m-auto search">
        <form method="POST" action="/search/" class="bg-indigo-800 px-1 relative rounded  " enctype="multipart/form-data"  >
          {%csrf_token%}
          <button id="capture_image"> <span class="iconify text-2xl absolute  top-2 right-20"  data-icon="mdi-camera"></span> </button>
          <label for="search" hidden>Search</label>
          <input class=" pl-5 py-1 focus:outline-none  rounded" type="search" placeholder="Search for product" name="query">
          <div class="absolute px-5 py-5 z-10 hidden bg-gray-100" id="upload_model" >  <span id="close_icon"class=" absolute right-0 top-[-5px] text-3xl text-red-800">&times;</span> <input class=" text-sm font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" type="file" name="image"></div>
          <input class="px-2 rounded  text-white hover:point hover:bg-indigo-600 py-2 px-1" type="submit" value="Search">
        </form>
      </div>
      <!-- Search form end -->
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">  
        {% main_nav %}
      </nav>
      <div class="nav-button">

      
     <a href="{% url 'store:cart_view'%}" 
     <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
      <span class="iconify" data-icon="mdi-cart-plus"></span> 
      Cart
      <span>{{cart.cart_len}}</span>
      </button>
    </a>
      <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        {% if request.user.is_authenticated %}
        <span class="iconify" data-icon="mdi-account"></span> <a href="{%url 'userProfile:my_account' %}" >My Account</a>
        {% else %} 
        <span class="iconify" data-icon="mdi-account"></span><a href="{%url 'userProfile:login' %}" >Login</a>

       {%endif%}
       
      </button>
      <button class="inline-flex items-center  bg-gray-100 border-0 py-1 px-2 rounded">
        {% if request.user.is_authenticated  %}
          {% if request.user.user_profile.is_vendor %}
        <span class="iconify" data-icon="mdi-store"></span> <a href="{%url 'userProfile:my_store' %}" >My Store</a>
        {% endif%}

       {%endif%}
      </button>
    </div>
    </div>
  </header>

backend/store/templates/includes/main_nav.html
{% for nav in main_nav %}
<a href="{% url 'store:category_detail' nav.slug %}" class="mr-5 hover:text-gray-900">{{nav.title}}</a>
{% endfor %}

backend/store/templates/includes/partial_Product.html
<div class="flex flex-wrap m-4">
{% for product in products %} 
<div class="lg:w-1/4 md:w-1/2 p-4 bg-white border mb-2 ml-2 hover:shadow-xl w-full">
  <a href="{% url 'store:Product_detail' product.id %}" class="block relative h-48 rounded overflow-hidden">
    {% if product.image %}
    <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{product.image.url}}">
    {%endif%}            </a>
  <a href="{% url 'store:Product_detail' product.id %}">
  <div class="mt-4">
    <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.category}}</h3>

    <h2 class="text-gray-900 title-font text-lg font-medium">{{product.title}}</h2>
    <div class=""><p class="mt-1 flex gap-2">{{product.price}}</p><a href="{% url 'userProfile:vendor_detail' product.added_by.id%}"> <p class="">{% firstof product.added_by.get_full_name  product.added_by.username%}</p></a></div>
  </div>
</a>
</div>
{%endfor%}
</div>