backend/main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store')),
    path('',include('userProfile.urls',namespace='vendor_detail'))
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/store/urls.py
from django.urls import re_path ,path 
from store.views import index,product_detail,department_categories,category,search_product,cart,add_to_cart
from store.views import remove_from_cart,change_quantity,checkout_page


app_name='store'

urlpatterns=[
    path('',index,name='home'),
    path('product/<int:id>/',product_detail,name='Product_detail'),
    path('department-categories/',department_categories,name='Department_Categories'),
    path('category/<str:slug>/',category,name='category_detail'),
    path('search/',search_product,name='search_product'),
    path('cart/',cart,name='cart_view'),
    path('add_to_cart/<int:product_id>/',add_to_cart,name='add_to_cart'),
    path("remove-from-cart/<str:product_id>/",remove_from_cart,name='remove_from_cart'),
    path('change_quantity/<str:product_id>/',change_quantity,name='change_quantity'),
    path('checkout/',checkout_page,name='checkout'),

]

backend/userProfile/urls.py
from django.urls import path
from userProfile.views import signup,my_account
from userProfile.views import my_store
from userProfile.views import add_product,edit_product,delete_product
from .views import vendor_detail 
from django.contrib.auth import views as auth_views


app_name='userProfile'

urlpatterns=[
    path('vendors/<int:pk>', vendor_detail,name='vendor_detail'),
    path('signup/', signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='user_profile/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('my_account/', my_account,name='my_account'),
    path('my_store/', my_store,name='my_store'),
    path('add_product/',add_product,name='add_product'),
    path('edit_product/<int:id>/',edit_product,name='edit_product'),
    path('delete_product/<int:id>/',delete_product,name='delete_product'),
]

backend/userProfile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
import uuid

class Pasal(models.Model):
    user = models.ForeignKey(User, related_name='Pasals', on_delete=models.CASCADE)
    pasal_reference_name = models.CharField(max_length=200)
    pasal_address = models.CharField(max_length=100)
    pasal_uid = models.UUIDField(default=uuid.uuid4, editable=False,unique=True)
    password=models.CharField(max_length=30)
    # class Meta:
    #     unique_together=
    def __str__(self):
        return f'{self.user.username} {self.pasal_reference_name}'

class UserProfile(models.Model):
    user=models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    is_vendor=models.BooleanField(default=False)
  
    def __str__(self):
        return self.user.username
    

backend/userProfile/forms.py
from django import forms
from store.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'title', 'description', 'price', 'image']
        
      

backend/userProfile/views.py
import django.contrib.auth.decorators
from django.shortcuts import render,redirect
from django.contrib.auth import login 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile
from store.models import Product,OrderItem,Order
from .forms import ProductForm
from django.contrib import messages
from django.utils.text import slugify

# Create your views here.
def vendor_detail(request,pk):
    user=User.objects.get(pk=pk)
    context={
        'user':user
    }
    return render(request, 'user_profile/vendor_detail.html',context)

def signup(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
        
            user_profile=UserProfile.objects.create(user=user)
            return redirect('store:home')
    else:
        form=UserCreationForm()
    return render(request,'user_profile/signup.html',{'form':form})

@login_required
def my_account(request):
    order=OrderItem.objects.filter(order__created_by=request.user)
    print(order)
    context={
        'orders':order
    }

    return render(request,'user_profile/my_account.html',context)


@login_required(login_url='/login/',redirect_field_name='next')
def my_store(request):
    seller_products= request.user.products.exclude(status=Product.DELETED)
    products_sold=OrderItem.objects.filter(product__added_by=request.user)
    context={
        "products":seller_products,
        "products_sold":products_sold
    }
    return render(request,'user_profile/my_store.html',context)



@login_required(login_url='/login/',redirect_field_name='next')
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            title=request.POST.get('title')
            product=form.save(commit=False)
            product.added_by=request.user
            product.slug=slugify(title) 
            form.save()
            messages.success(request, 'Product was added')
            return redirect('userProfile:my_store')
    else:
        form = ProductForm()

    context = {"title":"Add Product" ,'form': form}
    return render(request, 'user_profile/product_form.html', context)
@login_required
def edit_product(request,id):
    product=Product.objects.filter(added_by=request.user).get(id=id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES,instance=product)
        if form.is_valid():
            title=request.POST.get('title')
            product=form.save(commit=False)
            product.added_by=request.user
            product.slug=slugify(title) 
            messages.success(request, 'The changes was saved.')
            form.save()
            return redirect('userProfile:my_store')
    else:
        form = ProductForm(instance=product)
    context = {
        "title":"Edit Product",
        'form': form,
        'product':product
        }
    return render(request, 'user_profile/product_form.html', context)

@login_required
def delete_product(request, id):
    
    product = Product.objects.filter(added_by=request.user).get(id=id)
 
    
    product.status = Product.DELETED 
   
    product.save()

    messages.success(request, 'The product was deleted!')

    return redirect('userProfile:my_store')

# def VendorLogin(request):
#     if request.method=='POST':
#         form=UserCreationForm(request.POST)
#         form1=
#         if form.is_valid():
#             user=form.save()
#             login(request,user)
        
#             user_profile=UserProfile.objects.create(user=user)
#             return redirect('store:home')
#     else:
#         form=UserCreationForm()
#     return render(request,'user_profile/signup.html',{'form':form})

backend/userProfile/templates/user_profile/login.html
{% extends 'base.html' %}



{% block main_content %} 

{% load widget_tweaks %}
<main class="w-4/12 my-5 mx-auto">
    <div class="main-heading">
        <div class="w-full flex bg-gray-100 py-5  items-center">
            <a class="block px-5 py-2 flex-auto" href="{% url 'userProfile:login' %}"><h2 class="block px-5 text-white text-center bg-indigo-500   ">SignIn</h2></a>
            <a class="block flex-auto px-5" href="{% url 'userProfile:signup'%}"><h2 class="block   px-5 text-center ">SignUp</h2></a>
        </div>
    <h3 clas=" text-2xl ">Welcome! to Login Page!!</h2>
   <form class="" method="POST">
    {%csrf_token %}
    <div class="mb-4">
        <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Username</label>
        {{ form.username|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
    </div>
    <div class="mb-4">
        <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">password</label>
        {{ form.password|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
    </div>
    <button class="bg-indigo-500 w-2/5  text-white py-2 my-1 mx-auto" type="submit"> Login </button>
   </form>
</div>
</main>
{% endblock %}

backend/userProfile/templates/user_profile/my_account.html
{% extends 'base.html' %}

{% block main_content %} 

<main class=" w-4/5 mx-auto">
    <h2 class="text-2xl my-3">My Account</h2>   
  <section class="relative">
    {% if messages %}
    <div id="messages" class="absolute bottom-0 right-0 z-50">
        {% for message in messages %}
          <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4">
            <strong class="font-bold">{{ message.tags }}</strong>
            <span class="block sm:inline">{{ message }}</span>
            <button type="button" class="absolute px-2 py-2 top-0 right-0 mt-4 mr-4 text-lg font-semibold hover:text-gray-800" data-dismiss="alert">
              <span>&times;</span>
            </button>
          </div>
        {% endfor %}
      </div>

  {% endif %}
  {% if orders %}

  <h2 class="text-xl my-2 font-medium">Order Placed </h2>
<p class="text-xl">Your Ordered Products </p>
  <div class="flex flex-wrap -m-4  text-gray-700">
      {% for order in orders %} 
  
    <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
      <a href="{% url 'store:Product_detail' order.product.id %}" class="block relative h-48 rounded overflow-hidden">
        <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{{order.product.image.url}}">
      </a>
      <a href="{% url 'store:Product_detail' order.product.id %}">
      <div class="mt-1 my-2">
        <h3 class=" text-xs tracking-widest mb-1">{{order.order.created_by}}</h3>
        <p class=" title-font text-lg font-medium">{{order.product.title}}</p>
        <p class=" title-font text-lg font-medium"><strong>At Price:</strong>{{order.price}}</p>
        <p class="mt-1"><strong>{{order.order.created_at}}:</strong>{{order.order.status}}</p>
        <p class=" title-font text-lg font-medium"><strong>Quantity:</strong>{{order.quantity}}</p>

      </div>
    </a>
    
    </div>
    {%endfor%}
   
  </div>
  {% endif %}
  </section>
   <a class="bg-orange-800 px-3 py-2 text-white" href="{% url 'userProfile:logout'%}" >Logout</a>
</main>
{% endblock %}

backend/userProfile/templates/user_profile/my_store.html
{% extends 'base.html' %}

{% block main_content %} 
<main class=" w-4/5 mx-auto bg-gray-100 px-5 py-5">
    <h2 class="text-2xl my-3  font-medium inline-flex items-center"><span class="iconify" data-icon="mdi-store"></span>My Store</h2>
    <h3>Welcome! to your Store, <span class="font-medium">{% firstof request.user.get_full_name request.user.username %} </span></h3>
    <div class="add_product">
    
        <a href="{%url 'userProfile:add_product'%}"><button class="inline-flex items-center bg-indigo-800 text-white font-medium px-3 py-2 rounded hover:bg-indigo-400"><span class="iconify" data-icon="mdi-plus"></span>Add Product</button></a>
    </div>
    <!-- django messages  -->
    {% if messages %}
    
    <div class="message px-2 py-1 m-2">
        {% for message in messages%}
        <p class="px-2 py-1 bg-teal-800 text-white">{{message}}</p>
        {% endfor %}
    </div>
    {% endif%}

   <div class="my-store-products">
    <h2 class="text-xl border-b border-orange-300 my-2 inline-block">Listed Products</h2>
     
        <div class="flex flex-wrap m-4">
          {% for product in products %} 
          <div class="lg:w-1/4 md:w-1/2 p-4 bg-white border mb-2 ml-2 hover:shadow-xl w-full">
            <a href="{% url 'store:Product_detail' product.id %}" class="block relative h-48 rounded overflow-hidden">
              {% if product.image %}
              <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{product.image.url}}">
              {%endif%}            </a>
            <a href="{% url 'store:Product_detail' product.id %}">
            <div class="mt-4">
              <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.category}}</h3>
          
              <h2 class="text-gray-900 title-font text-lg font-medium">{{product.title}}</h2>
              <div class=""><p class="mt-1 text-gray-700 flex gap-2">{{product.price}}</p><a class="text-gray-500" href="{% url 'userProfile:vendor_detail' product.added_by.id%}"> <p class="">{% firstof product.added_by.get_full_name  product.added_by.username%}</p></a></div>
            </div>
          </a>
          </div>
          {%endfor%}
          </div>
        
   </div>
   <div class="my-store-ordered-products">
    <h2 class="text-xl border-b border-orange-300 my-2 inline-block">Ordered Products</h2>
      
        <div class="flex flex-wrap m-4">
          {% for product in products_sold %} 
          <div class="lg:w-1/4 md:w-1/2 p-4 bg-white border mb-2 ml-2 hover:shadow-xl w-full">
            <a href="{% url 'store:Product_detail' product.product.id %}" class="block relative h-48 rounded overflow-hidden">
              {% if product.image %}
              <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="{{product.product.image.url}}">
              {%endif%}            </a>
            <a href="{% url 'store:Product_detail' product.product.id %}">
            <div class="mt-4">
              <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.product.category}}</h3>
          
              <h2 class="text-gray-900 title-font text-lg font-medium">{{product.product.title}}</h2>
              <div class=""><p class="mt-1 flex gap-2">{{product.product.price}}</p><a href="{% url 'userProfile:vendor_detail' product.product.added_by.id%}"> <p class="">{% firstof product.added_by.get_full_name  product.added_by.username%}</p></a></div>
            </div>
          </a>
          </div>
          {%endfor%}
          </div>
   </div>
</main>
{% endblock %}

backend/userProfile/templates/user_profile/product_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block main_content %} 
<main class=" w-4/5 mx-auto">
    <h2 class="text-2xl my-3  font-medium inline-flex items-center"><span class="iconify" data-icon="mdi-store"></span>My Store</h2>
    {% if request.user.products %}
    <h3>Add product by filling form</h3>
    {% else  %}
   
    <h3>Welcome! You can add product and sell with us local and on global market. <span class="font-medium">{% firstof request.user.get_full_name request.user.username %} </span></h3>
    {% endif%}

    <div class="add_product">
        <form method="post" class="w-4/5 mx-auto" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-4">
                <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Category</label>
                {{ form.category|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
            </div>
            <div class="mb-4">
                <label for="{{ form.title.id_for_label }}" class="block text-gray-700 font-bold mb-2">Title</label>
                {{ form.title|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
            </div>
            <div class="mb-4">
                <label for="{{ form.description.id_for_label }}" class="block text-gray-700 font-bold mb-2">Description</label>
                {{ form.description|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
            </div>
            <div class="mb-4 flex gap-2 items-center">
                <div class=>
                <label for="{{ form.price.id_for_label }}" class="block text-gray-700 font-bold mb-2">Price</label>
                {{ form.price|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
                </div>
                    <div class=>
                    <label for="{{ form.price.id_for_label }}" class="block text-gray-700 font-bold mb-2">Discount (%)</label>
                    {{ form.price|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
                    </div>
                    <div class hidden=>
                        <label for="{{ form.price.id_for_label }}" class="block text-gray-700 font-bold mb-2">Displayed Price</label>
                        <input type="text" value="Rs.80.00" class="w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" readonly>
                    </div>
                    
            </div>
            <div class="mb-4">
                <label for="{{ form.image.id_for_label }}" class="block text-gray-700 font-bold mb-2">Image</label>
                {{ form.image|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
            </div>
            <div class="flex justify-between">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">{{title}}</button>
            {% if title == "Edit Product" %}
            <a href="{%url 'userProfile:delete_product' product.id %}" class="bg-red-500 gap-5 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete Product</a>
            {%endif%}
        </div>
        </form>
        
    
    </div>
   <div class="my-store-products">

   </div>
</main>
{% endblock %}

backend/userProfile/templates/user_profile/signup.html
{% extends 'base.html' %}


{% load widget_tweaks %}
{% block main_content %} 

<main class="w-4/12 my-5 mx-auto ">
   <div class="w-full bg-gray-100 py-5 flex items-center">
      <a class="block px-5 flex-auto py-2" href="{% url 'userProfile:login' %}"><h2 class="block px-5 text-center decoration-indigo-500">SignIn</h2></a>
      <a class="flex-auto px-5" href="{% url 'userProfile:signup'%}"><h2 class="block text-white  px-5 text-center bg-indigo-500">SignUp</h2></a>
  </div>
   <form class="" method="POST">
    {%csrf_token %}
    <div class="mb-4">
      <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Usernmae</label>
      {{ form.username|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
  </div>
  <div class="mb-4">
   <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Password</label>
   {{ form.password2|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
</div>
<div class="mb-4">
   <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Conform Password</label>
   {{ form.password1|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
</div>
    <button class="bg-indigo-500 w-2/5  text-white py-2 my-1 mx-auto" type="submit"> Register </button>
   </form>
</main>

{% endblock %}

backend/userProfile/templates/user_profile/vendor_detail.html
{% extends 'base.html' %}


{% block main_content %} 
<main class="w-5/6 bg-gray-100 mx-auto px-5">
<h2 class="text-xl my-2">{% firstof user.get_full_name user.username %}</h2>

<h3 class="text-2xl text-center">Your Listed Products</h3>
<div class="flex flex-wrap gap-1">
    {% for product in user.products.all  %} 

  <div class="lg:w-1/4 md:w-1/2 p-4 w-full bg-white border mb-5 hover:shadow-xl   ">
    <a href="{% url 'store:Product_detail' product.id%}" class="block relative h-48 rounded overflow-hidden">
      {% if product.image %}
      <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{{product.image.url}}">
      {%endif%}
    </a>
    <a href="{% url 'store:Product_detail' product.id %}">
    <div class="mt-4  px-2 py-1">
      <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.category}}</h3>
      <h2 class="text-gray-900 title-font text-lg font-medium">{{product.title}}</h2>
      <p class="mt-1">$16.00</p>
    </div>
  </a>
  
  </div>
  {%endfor%}
 
</div>

</main>
{% endblock %}

backend/userProfile/templates/user_profile/vendor_signup.html
{% extends 'base.html' %}


{% load widget_tweaks %}
{% block main_content %} 

<main class="w-4/12 my-5 mx-auto ">
   <div class="w-full bg-gray-100 py-5 flex items-center">
      <a class="block px-5 flex-auto py-2" href="{% url 'userProfile:login' %}"><h2 class="block px-5 text-center decoration-indigo-500">SignIn</h2></a>
      <a class="flex-auto px-5" href="{% url 'userProfile:signup'%}"><h2 class="block text-white  px-5 text-center bg-indigo-500">SignUp</h2></a>
  </div>
   <form class="" method="POST">
    {%csrf_token %}
    <div class="mb-4">
      <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Usernmae</label>
      {{ form.username|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
  </div>
  <div class="mb-4">
   <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Password</label>
   {{ form.password2|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
</div>
<div class="mb-4">
   <label for="{{ form.category.id_for_label }}" class="block text-gray-700 font-bold mb-2">Confirm Password</label>
   {{ form.password1|add_class:"w-full px-3 py-2 rounded-lg bg-gray-200 border-2 border-gray-200 focus:outline-none focus:border-blue-500" }}
</div>
    <button class="bg-indigo-500 w-2/5  text-white py-2 my-1 mx-auto" type="submit"> Register </button>
   </form>
</main>

{% endblock %}